### ISSUE TITLE
File 'MyProject/node_modules/react-promise-suspense/build/index.d.ts' is not a module.

### ISSUE THREAD

**Issue by zakdances** [vigzmv/react-promise-suspense#2]
Using this decleration:

`import usePromise from 'react-promise-suspense';`

produces

`File 'MyProject/node_modules/react-promise-suspense/build/index.d.ts' is not a module.`

**Comment by zakdances** [comment]
Any suggestions?

**Comment by vigzmv** [comment]
Hey, can you share more info on this, something that I can reproduce?
I have verified the build.

**Comment by Lynncubus** [comment]
#6 fixed this for me. 

Doesn't seem like `module.exports` is picked up as an export so it doesn't generate any exports in the declaration.

To reproduce generate a new react app with `create-react-app` with the typescript template and try using the module.
