### ISSUE TITLE
Transfer ownership 🚛

### ISSUE THREAD

**Issue by msereniti** [vigzmv/react-promise-suspense#26]
Following discussion from https://github.com/vigzmv/react-promise-suspense/pull/25.

> This is an experimental package and won't get any updates other than bug fixes, please feel free to fork or create your own for your use case.

As far as this package is not under development, forked it, covered with unit tests, typed, refactored and fixed several issues (such as https://github.com/vigzmv/react-promise-suspense/issues/8, https://github.com/vigzmv/react-promise-suspense/issues/9, https://github.com/vigzmv/react-promise-suspense/issues/10, https://github.com/vigzmv/react-promise-suspense/issues/13). Source code is available here https://github.com/phytonmk/react-promise-suspense.

Also published it as temporary package `@phytonmk/react-promise-suspense`, moved @vigzmv to contributors and set me as an author of new package (only to prevent developers contacting @vigzmv for issues of new package, suppose it is unwanted(???)).

Would be very glad @vigzmv if you will transfer ownership of github repo and npm package to me. It will allow me to maintain and develop the package further.

In case of any controversies or doubts I am open to discuss any other option (even publishing very same package under the different name) – my goal is to provide React developers with satisfactory level package for using promises inside of React.Suspense 😺

**Comment by vigzmv** [comment]
For full context, this was my complete [comment](https://github.com/vigzmv/react-promise-suspense/pull/25#issuecomment-1010166212).
>Thanks for the support @phytonmk. Could you update to provide default [] value to inputs.
This is an experimental package and won't get any updates other than bug fixes, please feel free to fork or create your own for your use case. Thanks.

Contributing to the existing package will be still the Best Practice. You can still create a new fork and package if you wish to.
I will take some time in the coming days to look at the open issues and fix them.
Thanks.

**Comment by msereniti** [comment]
Forked as [react-use-await](https://www.npmjs.com/package/react-use-await)
